::Const.Strings.MercenaryCompanyNames = [
	"The Last Legion of Cheliax",
	"Company of Cheliax",
	"Sons of Old Taldor",
	"The Taldan Blades",
	"The Last Andorans",
	"Free Company of Andoran",
	"Sons of Nidal",
	"The Nidalese Shadows",
	"The Grey Gardeners\' Orphans",
	"Free Company of Galt",
	"The Broken Swords of Brevoy",
	"Brevic Free Lances",
	"The Molthuni Levy",
	"Company of Molthune",
	"The Nirmathi Woodsmen",
	"Sons of Nirmathas",
	"The Prophets\' Guard",
	"Company of Druma",
	"The Isgeri Chain",
	"Sons of Isger",
	"Ustalav\'s Own",
	"The Ustalavic Watch",
	"The Numerian Salvagers",
	"Company of Numeria",
	"The Last Crusaders of Mendev",
	"The Mendevian Cross",
	"The Living God\'s Faithful",
	"Company of Razmiran",
	"The Kyonin Exiles",
	"The Elfgate Wardens",
	"Daughters of Irrisen",
	"The Irriseni Frost",
	"The Hold-Breakers",
	"Company of Belkzen",
	"The Varisian Wanderers",
	"Sons of Varisia",
	"The Free Ravounel",
	"Company of Ravounel",
	"The Last of the Wall",
	"Sentinels of Lastwall",
	"The Qadiran Freeriders",
	"Company of Qadira",
	"The Osirian Tomb-Guard",
	"Sons of Osirion",
	"The Thuvian Caravan",
	"Company of Thuvia",
	"The Godless of Rahadoum",
	"The Rahadoumi Free",
	"The Heirs of Nex",
	"Company of Nex",
	"The Gebbite Dead",
	"Sons of Geb",
	"The Sargavan Colonials",
	"Company of Sargava",
	"The Oprak Hobgoblins",
	"The Oprak Legion",
	"The Jalmeri Masters",
	"Company of Jalmeray",
	"The Hermean Exiles",
	"Sons of Hermea",
	"The Iobarian Riders",
	"Company of Iobaria",
	"The Red Mantis Cast-Offs",
	"The Mediogalti Blades",
	"The Heirs of Thassilon",
	"Sons of Thassilon",
	"The Sarkoris Reclaimers",
	"The Lost Sarkorians",
	"The Katapeshi Free Company",
	"Company of Katapesh",
	"The Pitax Free Blades",
	"Company of Pitax",
	"The Daggermark Poisoners",
	"Sons of Daggermark",
	"The Gralton Reclaimers",
	"Company of Gralton",
	"The Mivon Swordlords",
	"Sons of Mivon",
	"The Tymon Gladiators",
	"Company of Tymon",
	"The Masked of Vyre",
	"Company of Vyre"
];
::Const.Strings.FreeCompanyNames = clone ::Const.Strings.MercenaryCompanyNames;
::logInfo("Golarion: " + ::Const.Strings.MercenaryCompanyNames.len() + " mercenary companies loaded (nations that fell)");
